"""adding app version to conn

Revision ID: 2415b7759f3f
Revises: ffa6672c0f8a
Create Date: 2024-12-27 14:27:38.227810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import src


# revision identifiers, used by Alembic.
revision: str = '2415b7759f3f'
down_revision: Union[str, None] = 'ffa6672c0f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows_connection', sa.Column('appVersion', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows_connection', 'appVersion')
    # ### end Alembic commands ###

