"""workflow execution added

Revision ID: 29816fbebd1f
Revises: 5469feaf9176
Create Date: 2025-01-03 05:16:00.734626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import agentic_workflow


# revision identifiers, used by Alembic.
revision: str = '29816fbebd1f'
down_revision: Union[str, None] = '5469feaf9176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows_execution',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('orgId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflowId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflowRunId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflowId', 'workflowRunId', name='unique_workflow_id_workflow_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows_execution')
    # ### end Alembic commands ###

