"""app and conn tables

Revision ID: 3aca3b352491
Revises: 
Create Date: 2024-12-24 21:34:36.459696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import src


# revision identifiers, used by Alembic.
revision: str = '3aca3b352491'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows_app',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('orgId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth', src.db.utils.utils.PydanticJSONType(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('triggers', src.db.utils.utils.PydanticJSONType(), nullable=True),
    sa.Column('actions', src.db.utils.utils.PydanticJSONType(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows_connection',
    sa.Column('createdBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedBy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('orgId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('appId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logoUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credentials', src.db.utils.utils.PydanticJSONType(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['workflows_app.id'], name='fk_app_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows_connection')
    op.drop_table('workflows_app')
    # ### end Alembic commands ###

