"""updated app and conn tables

Revision ID: ffa6672c0f8a
Revises: 3aca3b352491
Create Date: 2024-12-25 19:01:48.723743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import src


# revision identifiers, used by Alembic.
revision: str = 'ffa6672c0f8a'
down_revision: Union[str, None] = '3aca3b352491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows_app', sa.Column('endpointUrl', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('workflows_connection', 'logoUrl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows_connection', sa.Column('logoUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workflows_app', 'endpointUrl')
    # ### end Alembic commands ###

